using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace XTRWorkSite.WSObjects.Enums
{
    //Valores do enumerado imProfileAttributeID (IManage)
    public enum XTR_EnumProfileAttributeID
    {
        imProfileDatabase = 0,
        imProfileDocNum = 1,
        imProfileVersion = 2,
        imProfileDescription = 3,
        imProfileName = 4,
        imProfileAuthor = 5,
        imProfileOperator = 6,
        imProfileType = 7,
        imProfileClass = 8,
        imProfileSubClass = 9,
        imProfileEditDate = 10,
        imProfileCreateDate = 11,
        imProfileRetainDays = 12,
        imProfileSize = 13,
        imProfileIndexable = 14,
        imProfileIsRelated = 15,
        imProfileLocation = 16,
        imProfileDefaultSecurity = 17,
        imProfileLastUser = 18,
        imProfileInUseBy = 19,
        imProfileNetNode = 20,
        imProfileInUse = 21,
        imProfileCheckedOut = 22,
        imProfileArchived = 23,
        imProfileComment = 24,
        imProfileCustom1 = 25,
        imProfileCustom2 = 26,
        imProfileCustom3 = 27,
        imProfileCustom4 = 28,
        imProfileCustom5 = 29,
        imProfileCustom6 = 30,
        imProfileCustom7 = 31,
        imProfileCustom8 = 32,
        imProfileCustom9 = 33,
        imProfileCustom10 = 34,
        imProfileCustom11 = 35,
        imProfileCustom12 = 36,
        imProfileCustom13 = 37,
        imProfileCustom14 = 38,
        imProfileCustom15 = 39,
        imProfileCustom16 = 40,
        imProfileCustom17 = 41,
        imProfileCustom18 = 42,
        imProfileCustom19 = 43,
        imProfileCustom20 = 44,
        imProfileCustom21 = 45,
        imProfileCustom22 = 46,
        imProfileCustom23 = 47,
        imProfileCustom24 = 48,
        imProfileCustom25 = 49,
        imProfileCustom26 = 50,
        imProfileCustom27 = 51,
        imProfileCustom28 = 52,
        imProfileCustom29 = 53,
        imProfileCustom30 = 54,
        imProfileCustom1Description = 60,
        imProfileCustom2Description = 61,
        imProfileCustom3Description = 62,
        imProfileCustom4Description = 63,
        imProfileCustom5Description = 64,
        imProfileCustom6Description = 65,
        imProfileCustom7Description = 66,
        imProfileCustom8Description = 67,
        imProfileCustom9Description = 68,
        imProfileCustom10Description = 69,
        imProfileCustom11Description = 70,
        imProfileCustom12Description = 71,
        imProfileCustom29Description = 72,
        imProfileCustom30Description = 73,
        imProfileAuthorDescription = 74,
        imProfileOperatorDescription = 75,
        imProfileTypeDescription = 76,
        imProfileClassDescription = 77,
        imProfileSubClassDescription = 78,
        imProfileLastUserDescription = 79,
        imProfileInUseByDescription = 80,
        imProfileEditTime = 81,
        imProfileExtension = 82,
        imProfileFullText = 83,
        imProfileSubType = 84,
        imProfileEditProfileTime = 85,
        imProfileContainerID = 89,
        imProfileCustom31 = 96,
        imProfileMarkedForArchive = 97,
        imProfileEchoEnabled = 98,
        imProfileAccessTime = 99,
        imProfileMessageUniqueID = 100,
        imProfileIsExternal = 101,
        imProfileHasAttachment = 102,
        imProfileExternalAsNormal = 103,
        imProfileProjectItemSID = 104,
        imProfileProjectItemParentSID = 105,
        imProfileCheckoutPath = 106,
        imProfileCheckoutDueDate = 107,
        imProfileCheckoutComments = 108,
        imProfileCheckoutWhen = 109,
        imProfileQuickRetrieve = 110,
        imProfileFrozen = 111,
        imProfileDeclareDate = 112,
        imProfileFileCreateDate = 113,
        imProfileFileModifyDate = 114,
        imProfileSystemCreateDate = 115,
        imProfileSystemModifyDate = 116,
        imProfileRestorable = 117,
        imProfileHipaaCompliant = 118,
        imProfileFtLanguageId = 119,
    }
}
