using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace XTRWorkSite.WSObjects.Enums
{
    //valores do enumerado AttributeID (IManAdmin)
    public enum XTR_EnumAttributeID
    {
        nrDatabase = 0,
        nrDocNum = 1,
        nrVersion = 2,
        nrDescription = 3,
        nrName = 4,
        nrAuthor = 5,
        nrOperator = 6,
        nrType = 7,
        nrClass = 8,
        nrSubClass = 9,
        nrEditDate = 10,
        nrCreateDate = 11,
        nrRetainDays = 12,
        nrSize = 13,
        nrIndexable = 14,
        nrIsRelated = 15,
        nrLocation = 16,
        nrDefaultSecurity = 17,
        nrLastUser = 18,
        nrInUseBy = 19,
        nrNetNode = 20,
        nrInUse = 21,
        nrCheckedOut = 22,
        nrArchived = 23,
        nrComment = 24,
        nrCustom1 = 25,
        nrCustom2 = 26,
        nrCustom3 = 27,
        nrCustom4 = 28,
        nrCustom5 = 29,
        nrCustom6 = 30,
        nrCustom7 = 31,
        nrCustom8 = 32,
        nrCustom9 = 33,
        nrCustom10 = 34,
        nrCustom11 = 35,
        nrCustom12 = 36,
        nrCustom13 = 37,
        nrCustom14 = 38,
        nrCustom15 = 39,
        nrCustom16 = 40,
        nrCustom17 = 41,
        nrCustom18 = 42,
        nrCustom19 = 43,
        nrCustom20 = 44,
        nrCustom21 = 45,
        nrCustom22 = 46,
        nrCustom23 = 47,
        nrCustom24 = 48,
        nrCustom25 = 49,
        nrCustom26 = 50,
        nrCustom27 = 51,
        nrCustom28 = 52,
        nrCustom29 = 53,
        nrCustom30 = 54,
        nrCustom1Description = 60,
        nrCustom2Description = 61,
        nrCustom3Description = 62,
        nrCustom4Description = 63,
        nrCustom5Description = 64,
        nrCustom6Description = 65,
        nrCustom7Description = 66,
        nrCustom8Description = 67,
        nrCustom9Description = 68,
        nrCustom10Description = 69,
        nrCustom11Description = 70,
        nrCustom12Description = 71,
        nrCustom29Description = 72,
        nrCustom30Description = 73,
        nrAuthorDescription = 74,
        nrOperatorDescription = 75,
        nrTypeDescription = 76,
        nrClassDescription = 77,
        nrSubClassDescription = 78,
        nrLastUserDescription = 79,
        nrInUseByDescription = 80,
        nrEditTime = 81,
        nrExtension = 82,
        nrSubType = 83,
        nrContainerID = 84,
        nrCustom31 = 85,
        nrEditProfileTime = 86,
        nrAccessTime = 87,
        nrMessageUniqueID = 88,
        nrIsExternal = 89,
        nrHasAttachment = 90,
        nrExternalAsNormal = 91,
        nrProjectItemSID = 92,
        nrProjectItemParentSID = 93,
        nrCheckoutPath = 94,
        nrCheckoutDueDate = 95,
        nrCheckoutComments = 96,
        nrCheckoutWhen = 97,
        nrQuickRetrieve = 98,
        nrFrozen = 99,
        nrDeclareDate = 100,
        nrFileCreateDate = 101,
        nrFileModifyDate = 102,
        nrSystemCreateDate = 103,
        nrSystemModifyDate = 104,
        nrRestorable = 105,
    }
}
